Tickets = [
    {"id": "1051",
     "user": "Steve; Marketing",
     "priority": "Medium",
     "issue": "Unable to post content to social media platforms; error message: 'No internet access'",
     "option_1": "Check router, restart if needed",
     "option_2": "Reset users password",
     "correct_option": "option_1",
     "success_message": "You check the router, find that it is down and restarted it, now marketing has internet access again",
     "fail_message": "You reset the users password, but they still cannot connect to the internet and post",
     "time_taken": 0.5
     },
     {"id": "1054",
      "user": "John; Finance",
      "priority": "High",
      "issue": "Unable to access internal finance database, error message: 'Server not found'",
      "option_1": "Check if server is down, restart if needed",
      "option_2": "Run antivirus scan on users computer",
      "correct_option": "option_1",
      "success_message": "You check the server, find that it is down and restart it, finance database comes back online",
      "fail_message": "You run an antivirus scan which takes 2 hours, but nothing is found and database is still unreachable",
      "time_taken": 1
      },
      {"id": "1152",
       "user": "Joseph; HR",
       "priority": "Low",
       "issue": "Unable to login to HR portal",
       "option_1": "Restart all servers",
       "option_2": "Reset users login details",
       "correct_option": "option_2",
       "success_message": "You reset the users login details, they can now login to the HR portal",
       "fail_message": "You restart all servers, cutting network access for all users, user cannot login to HR portal still",
       "time_taken": 0.5
      },
      {"id": "1155",
       "user": "Tim; Engineering",
       "priority": "Critical",
       "issue": "Whole building unable to connect to internet and file servers are down",
       "option_1": "Run to server room, restart servers and check router",
       "option_2": "Call isp and wait for them to fix the issue",
       "correct_option": "option_1",
       "success_message": "You get to the server room, restart the servers and have to rewire the cables to the router, after 30 minutes the building is back online",
       "fail_message": "You call the isp, report the issue, they say someone will be over in 3 hours, building is offline for 4 hours, your manager is not happy",
       "time_taken": 1.5
       },
       {"id": "1243",
        "user": "Paul; Software Developer",
        "priority": "High",
        "issue": "Unable to access vs code, error message: 'Access denied'",
        "option_1": "Check if user has the correct permissions, update if needed",
        "option_2": "Contact finance to check that they have paid for another year",
        "correct_option": "option_1",
        "success_message": "You check the users permissions; find that they have been removed from the vs code group, you add them back to the group and they can now access vs code again",
        "fail_message": "You contact finance, they say that they have paid and to not bother them",
        "time_taken": 0.5
        },
        {"id": "1334",
         "user": "Sarah; Sales",
         "priority": "Medium",
         "issue": "Unable to access shared drive, error message: 'Drive not found'",
         "option_1": "Remap network drive on device",
         "option_2": "Check if the user has the correct permissions, update if needed",
         "correct_option": "option_1",
         "success_message": "You remap the network drive on the users device, they can now access the shared drive",
         "fail_message": "You check the users permissions, they have the correct permissions but still cannot access the shared drive",
         "time_taken": 0.5
        },
        {"id": "1337",
         "user": "David; IT Support",
         "priority": "Low",
         "issue": "Unable to access email, error message: 'Mailbox not found'",
         "option_1": "Check if the user has the correct permissions, update if needed",
         "option_2": "Check if the users mailbox is full, delete old emails if needed",
         "correct_option": "option_1",
         "success_message": "You check the users permissions, find that they have been removed from the email group, you add them back and they can now access their email",
         "fail_message": "You check the users mailbox, find that it is not full and they still cannot access their email",
         "time_taken": 0.5
        },
        {"id": "1444",
         "user": "Emma; Marketing",
         "priority": "Critical",
         "issue": "Unable to access company website, error message: 'Server not found'",
         "option_1": "Check if server is down, restart if needed",
         "option_2": "Check if the domain name has expired, renew if needed",
         "correct_option": "option_1",
         "success_message": "You check the server, find that it is down and restart it, the company website is back online",
         "fail_message": "You check the domain name, find that it has not expired and the website is still down",
         "time_taken": 1
        },
        {"id": "1555",
         "user": "Michael; Finance",
         "priority": "High",
         "issue": "Unable to access company bank account, error message: 'Cannot connect to bank'",
         "option_1": "Check if finance switch is down, restart if needed",
         "option_2": "Remote into users computer, update their os and bios",
         "correct_option": "option_1",
         "success_message": "You check the finance switch, find that it is down, restart it and now finance floor can access the internet",
         "fail_message": "You remote into the users computer, update their os and bios, but they still cannot access the company bank account",
         "time_taken": 2
        },
        {"id": "1666",
         "user": "Jessica; HR",
         "priority": "Medium",
         "issue": "Unable to access meeting notes, error message: 'File not found'",
         "option_1": "Check recent backups, restore if needed",
         "option_2": "check the meeting room for the notes",
         "correct_option": "option_1",
         "success_message": "You check the recent backups, see that Joseph deleted them, you restore the notes",
         "fail_message": "You check the meeting room, but the notes are not there",
         "time_taken": 0.5
        },
        {"id": "1777",
         "user": "Daniel; Engineering",
         "priority": "Critical",
         "issue": "Unable to access latest mockup, error message: 'permission denied'",
         "option_1": "Ask engineering manager what the latest mockup is",
         "option_2": "Check if the user has the correct permissions, update if needed",
         "correct_option": "option_2",
         "success_message": "You check the user permissions, find that Daniel has been removed from the engineering group, you add him back and he can now access the mockup",
         "fail_message": "You ask the engineering manager, he says he cannot tell you what the latest mockup is and to get on with helping Daniel",
         "time_taken": 0.5
        },
        {"id": "1765",
         "user": "Samantha; Sales",
         "priority": "High",
         "issue": "Unable to access sales report, error message: 'Database does not exist'",
         "option_1": "Restart file server",
         "option_2": "Check through recent backups for the sales report, restore if needed",
         "correct_option": "option_2",
         "success_message": "You checl the recent backups, find that an intern deleted the sales report, you restore it and sales can now access it",
         "fail_message": "You restart the file server, but the sales report is still not accessible",
         "time_taken": 1
         },
         {"id": "1842",
          "user": "Olivia; Marketing",
          "Priority": "Medium",
          "issue": "Social media campaign drafts missing, error message: 'Files not found'",
          "option_1": "Check backups for the drafts, restore if needed",
          "option_2": "Restart Router on Marketing floor",
          "correct_option": "option_1",
          "success_message": "You check the backups, find that the drafts were deleted and renamed, you restore them and marketing can now access them",
          "fail_message": "You restart the router, but the drafts are still missing",
          "time_taken": 1
         },
         {"id": "1856",
          "user": "Liam; Finance",
          "priority": "Critical",
          "issue": "Finance system is unable to process payments, error message: 'Outdated tokens'",
          "option_1": "Check if finance switch is down, restart if needed",
          "option_2": "Contact finance system provider to update tokens and restart system",
          "correct_option": "option_2",
          "success_message": "You contact the finance system provider, they update the tokens and restart the system, finance can now process payments",
          "fail_message": "You check the finance switch, find that it is not down and the system still cannot process payments",
          "time_taken": 2
          },
          {"id": "1867",
           "user": "Bob; Apprentice",
           "priority": "Low",
           "issue": "Needs access to company software and database, error message 'Access denied'",
           "option_1": "Add Bob to correct groups and ensure he has access to company software and databases",
           "option_2": "Reset Bob's Password",
           "correct_option": "option_1",
           "success_message": "You add Bob to the correct groups and ensure he has access to company software and databases, he can now be successful.",
           "fail_message": "You reset Bob's password, but he still cannot access company software and databases",
           "time_taken": 0.5
           },

        ]