Tickets = [
    {"id": "1051",
     "user": "Steve; Marketing",
     "priority": "Medium",
     "issue": "Unable to post content to social media platforms; error message: 'No internet access'",
     "option_1": "Check router, restart if needed",
     "option_2": "Reset users password",
     "correct_option": "option_1",
     "success_message": "You check the router, find that it is down and restarted it, now marketing has internet access again",
     "fail_message": "You reset the users password, but they still cannot connect to the internet and post",
     },
     {"id": "1054",
      "user": "John; Finance",
      "priority": "High",
      "issue": "Unable to access internal finance database, error message: 'Server not found'",
      "option_1": "Check if server is down, restart if needed",
      "option_2": "Run antivirus scan on users computer",
      "correct_option": "option_1",
      "success_message": "You check the server, find that it is down and restart it, finance database comes back online",
      "fail_message": "You run an antivirus scan which takes 2 hours, but nothing is found and database is still unreachable",
      },
      {"id": "1152",
       "user": "Joseph; HR",
       "priority": "Low",
       "issue": "Unable to login to HR portal",
       "option_1": "Restart all servers",
       "option_2": "Reset users login details",
       "correct_option": "option_2",
       "success_message": "You reset the users login details, they can now login to the HR portal",
       "fail_message": "You restart all servers, cutting network access for all users, user cannot login to HR portal still",
      },
      {"id": "1155",
       "user": "Tim; Engineering",
       "priority": "Critical",
       "issue": "Whole building unable to connect to internet and file servers are down",
       "option_1": "Run to server room, restart servers and check router",
       "option_2": "Call isp and wait for them to fix the issue",
       "correct_option": "option_1",
       "success_message": "You get to the server room, restart the servers and have to rewire the cables to the router, after 30 minutes the building is back online",
       "fail_message": "You call the isp, report the issue, they say someone will be over in 3 hours, building is offline for 4 hours, your manager is not happy",
       },
       {"id": "1243",
        "user": "Paul; Software Developer",
        "priority": "High",
        "issue": "Unable to access vs code, error message: 'Access denied'",
        "option_1": "Check if user has the correct permissions, update if needed",#
        "option_2": "Contact finance to check that they have paid for another year",
        "correct_option": "option_1",
        "success_message": "You check the users permissions; find that they have been removed from the vs code group, you add them back to the group and they can no access vs code again",
        "fail_message": "You contact finance, they say that they have paid and to not bother them",
        },

]