Tickets = [
    {"id": "1051",
     "user": "Steve; Marketing",
     "priority": "Medium",
     "issue": "Unable to post content to social media platforms; error message: 'No internet access'",
     "option_1": "Check router, restart if needed",
     "option_2": "Reset users password",
     "correct_option": "option_1",
     "success_message": "You check the router, find that it is down and restarted it, now marketing has internet access again",
     "fail_message": "You reset the users password, but they still cannot connect to the internet and post",
     "time_taken": 0.5
     },
     {"id": "1054",
      "user": "John; Finance",
      "priority": "High",
      "issue": "Unable to access internal finance database, error message: 'Server not found'",
      "option_1": "Check if server is down, restart if needed",
      "option_2": "Run antivirus scan on users computer",
      "correct_option": "option_1",
      "success_message": "You check the server, find that it is down and restart it, finance database comes back online",
      "fail_message": "You run an antivirus scan which takes 2 hours, but nothing is found and database is still unreachable",
      "time_taken": 1
      },
      {"id": "1152",
       "user": "Joseph; HR",
       "priority": "Low",
       "issue": "Unable to login to HR portal",
       "option_1": "Restart all servers",
       "option_2": "Reset users login details",
       "correct_option": "option_2",
       "success_message": "You reset the users login details, they can now login to the HR portal",
       "fail_message": "You restart all servers, cutting network access for all users, user cannot login to HR portal still",
       "time_taken": 0.5
      },
      {"id": "1155",
       "user": "Tim; Engineering",
       "priority": "Critical",
       "issue": "Whole building unable to connect to internet and file servers are down",
       "option_1": "Run to server room, restart servers and check router",
       "option_2": "Call isp and wait for them to fix the issue",
       "correct_option": "option_1",
       "success_message": "You get to the server room, restart the servers and have to rewire the cables to the router, after 30 minutes the building is back online",
       "fail_message": "You call the isp, report the issue, they say someone will be over in 3 hours, building is offline for 4 hours, your manager is not happy",
       "time_taken": 1.5
       },
       {"id": "1243",
        "user": "Paul; Software Developer",
        "priority": "High",
        "issue": "Unable to access vs code, error message: 'Access denied'",
        "option_1": "Check if user has the correct permissions, update if needed",
        "option_2": "Contact finance to check that they have paid for another year",
        "correct_option": "option_1",
        "success_message": "You check the users permissions; find that they have been removed from the vs code group, you add them back to the group and they can now access vs code again",
        "fail_message": "You contact finance, they say that they have paid and to not bother them",
        "time_taken": 0.5
        },
        {"id": "1334",
         "user": "Sarah; Sales",
         "priority": "Medium",
         "issue": "Unable to access shared drive, error message: 'Drive not found'",
         "option_1": "Remap network drive on device",
         "option_2": "Check if the user has the correct permissions, update if needed",
         "correct_option": "option_1",
         "success_message": "You remap the network drive on the users device, they can now access the shared drive",
         "fail_message": "You check the users permissions, they have the correct permissions but still cannot access the shared drive",
         "time_taken": 0.5
        },
        {"id": "1337",
         "user": "David; IT Support",
         "priority": "Low",
         "issue": "Unable to access email, error message: 'Mailbox not found'",
         "option_1": "Check if the user has the correct permissions, update if needed",
         "option_2": "Check if the users mailbox is full, delete old emails if needed",
         "correct_option": "option_1",
         "success_message": "You check the users permissions, find that they have been removed from the email group, you add them back and they can now access their email",
         "fail_message": "You check the users mailbox, find that it is not full and they still cannot access their email",
         "time_taken": 0.5
        },
        {"id": "1444",
         "user": "Emma; Marketing",
         "priority": "Critical",
         "issue": "Unable to access company website, error message: 'Server not found'",
         "option_1": "Check if server is down, restart if needed",
         "option_2": "Check if the domain name has expired, renew if needed",
         "correct_option": "option_1",
         "success_message": "You check the server, find that it is down and restart it, the company website is back online",
         "fail_message": "You check the domain name, find that it has not expired and the website is still down",
         "time_taken": 1
        },
        {"id": "1555",
         "user": "Michael; Finance",
         "priority": "High",
         "issue": "Unable to access company bank account, error message: 'Cannot connect to bank'",
         "option_1": "Check if finance switch is down, restart if needed",
         "option_2": "Remote into users computer, update their os and bios",
         "correct_option": "option_1",
         "success_message": "You check the finance switch, find that it is down, restart it and now finance floor can access the internet",
         "fail_message": "You remote into the users computer, update their os and bios, but they still cannot access the company bank account",
         "time_taken": 2
        },
        {"id": "1666",
         "user": "Jessica; HR",
         "priority": "Medium",
         "issue": "Unable to access meeting notes, error message: 'File not found'",
         "option_1": "Check recent backups, restore if needed",
         "option_2": "check the meeting room for the notes",
         "correct_option": "option_1",
         "success_message": "You check the recent backups, see that Joseph deleted them, you restore the notes",
         "fail_message": "You check the meeting room, but the notes are not there",
         "time_taken": 0.5
        },
        {"id": "1777",
         "user": "Daniel; Engineering",
         "priority": "Critical",
         "issue": "Unable to access latest mockup, error message: 'permission denied'",
         "option_1": "Ask engineering manager what the latest mockup is",
         "option_2": "Check if the user has the correct permissions, update if needed",
         "correct_option": "option_2",
         "success_message": "You check the user permissions, find that Daniel has been removed from the engineering group, you add him back and he can now access the mockup",
         "fail_message": "You ask the engineering manager, he says he cannot tell you what the latest mockup is and to get on with helping Daniel",
         "time_taken": 0.5
        },
        {"id": "1765",
         "user": "Samantha; Sales",
         "priority": "High",
         "issue": "Unable to access sales report, error message: 'Database does not exist'",
         "option_1": "Restart file server",
         "option_2": "Check through recent backups for the sales report, restore if needed",
         "correct_option": "option_2",
         "success_message": "You checl the recent backups, find that an intern deleted the sales report, you restore it and sales can now access it",
         "fail_message": "You restart the file server, but the sales report is still not accessible",
         "time_taken": 1
         },
         {"id": "1842",
          "user": "Olivia; Marketing",
          "priority": "Medium",
          "issue": "Social media campaign drafts missing, error message: 'Files not found'",
          "option_1": "Check backups for the drafts, restore if needed",
          "option_2": "Restart Router on Marketing floor",
          "correct_option": "option_1",
          "success_message": "You check the backups, find that the drafts were deleted and renamed, you restore them and marketing can now access them",
          "fail_message": "You restart the router, but the drafts are still missing",
          "time_taken": 1
         },
         {"id": "1856",
          "user": "Liam; Finance",
          "priority": "Critical",
          "issue": "Finance system is unable to process payments, error message: 'Outdated tokens'",
          "option_1": "Check if finance switch is down, restart if needed",
          "option_2": "Contact finance system provider to update tokens and restart system",
          "correct_option": "option_2",
          "success_message": "You contact the finance system provider, they update the tokens and restart the system, finance can now process payments",
          "fail_message": "You check the finance switch, find that it is not down and the system still cannot process payments",
          "time_taken": 2
          },
          {"id": "1867",
           "user": "Bob; Apprentice",
           "priority": "Low",
           "issue": "Needs access to company software and database, error message 'Access denied'",
           "option_1": "Add Bob to correct groups and ensure he has access to company software and databases",
           "option_2": "Reset Bob's Password",
           "correct_option": "option_1",
           "success_message": "You add Bob to the correct groups and ensure he has access to company software and databases, he can now be successful.",
           "fail_message": "You reset Bob's password, but he still cannot access company software and databases",
           "time_taken": 0.5
           },
           {"id": "1888",
            "user": "Alice; HR",
            "priority": "High",
            "issue": "Unable to access hiring portal, error message: 'Network Connection Lost'",
            "option_1": "Check if the network switch is down, restart if needed",
            "option_2": "Contact hiring portal provider to check for outages",
            "correct_option": "option_1",
            "success_message": "You check the network switch, find that it is down and restart it, HR can now access the hiring portal",
            "fail_message": "You contact the hiring portal provider, they say there are no outages and HR still cannot access the hiring portal",
            "time_taken": 1
            },
            {"id": "1964",
            "user": "Charlie; IT",
            "priority": "Medium",
            "issue": "Unable to save files, error message: 'Disk Full'",
            "option_1": "Check disk space, remove unnecessary files if needed",
            "option_2": "Run a virus scan to check for malware",
            "correct_option": "option_1",
            "success_message": "You check the disk space, find that it is full and remove unnecessary files, Charlie's files can now be saves",
            "fail_message": "You run a virus scan, but find no malware and Charlie still cannot save files",
            "time_taken": 1
            },
            {"id": "1975",
             "user": "Diana; Marketing",
             "priority": "High",
             "issue": "unable to access marketing analytics, error message: 'Access Denied'",
             "option_1": "Check if Diana has correct permissions, update if needed",
             "option_2": "Check if marketing server is down, restart if needed",
             "correct_option": "option_1",
             "success_message": "You check Diana's permissions, find that she has been removed from the marketing group, you add her back and she can now access marketing analytics",
             "fail_message": "You check the marketing server, find that it is not down and Diana still cannot access marketing analytics",
             "time_taken": 0.5
             },
             {"id": "1987",
              "user": "Edward; QA",
              "priority": "High",
              "issue": "Unable to access QA testing sandbox, error message: 'Unable to connect to sandbox'",
              "option_1": "Restart QA testing sandbox server",
              "option_2": "ASk finance to check that they still have a valid subscription for the sandbox software",
              "correct_option": "option_1",
              "success_message": "You restart the QA testing sandbox server, and now Edward can access it",
              "fail_message": "You ask finance about the subscription, they say it is still valid but Edward still cannot access the QA testing sandbox",
              "time_taken": 0.5,
             },
             {"id": "1995",
              "user": "Dylan; Project Management",
              "priority": "Medium",
              "issue": "Unable to access gannt charts and project timelines, error message: 'Outdated software version'",
              "option_1": "Do a virus scan on the users computer",
              "option_2": "Update the project management software to the latest version",
              "correct_option": "option_2",
              "success_message": "You update the project management software to the latest version, now Dylan can access the gannt charts and project timelines",
              "fail_message": "You do a virus scan on the users computer, but find no viruses and Dylan still cannot access the gannt charts and project timelines",
              "time_taken": 1
              },
              {"id": "2001",
               "user": "Steve; Fulfillment",
               "priority": "Critical",
               "issue": "Unable to access warehous management systems, inventory tracking and order processing, error message: 'Unknown fatal error'",
               "option_1": "Restart physical and cloud servers,report bug to software developers to fix the issue",
               "option_2": "Ensure that the connection from the servers to the warehouse is working, if not fix the connection",
               "correct_option": "option_1",
               "success_message": "You restart the physical and cloud servers, report the bug to the software developers who fix the issue, steve can now access the warehouse management systems, inventory tracking and order processing",
               "fail_message": "You check the connection from the servers to the warehouse, find that it is working and steve still cannot access the warehouse management systems, inventory tracking and order processing",
               "time_taken": 2,
               },
               {"id": "2009",
                "user": "Rachel; Customer Support",
                "priority": "High",
                "issue": "Unable to access customer support ticketing system, error message: 'Storage full'",
                "option_1": "Check storage space, remove unnecessary files",
                "option_2": "Contact ticketing system provider to check for any current outages",
                "correct_option": "option_1",
                "success_message": "You check the storage space, find that it is full and remove unnecessary files, Rachel can now access the customer support ticketing system",
                "fail_message": "You contact the ticketing system provider, they say there are no outages and Rachel still cannot access the customer support ticketing system",
                "time_taken": 1
                },
                {"id": "2013",
                 "user": "Tom; Customer Relations",
                 "priority": "Medium",
                 "issue": "Unable to make calls to customers, error message: 'Number Expired'",
                 "option_1": "Buy a new phone for the customer relations team",
                 "option_2": "Contact mobile provider to check if the number has expired, if it has then renew the numhber",
                 "correct_option": "option_2",
                 "success_message": "You contact the mobile provider, they say that the number has expire, they renew the number and now Tom can make calls to customer again",
                 "fail_message": "You buy a new phone for the customer relations team, but Tom still cannot make calls to customers, the phone is redundant",
                 "time_taken": 1
                },
                {"id": "2020",
                 "user": "Anna; logistics",
                 "priority": "Critical",
                 "issue": "Unable to access delivery tracking system, error message: 'Account deactivated'",
                 "option_1": "Check if Anna has the correct permissions, update if needed",
                 "option_2": "Reactivate Anna's account in the delivery tracking system",
                 "correct_option": "option_2",
                 "success_message": "You reactivate Anna's account in the delivery tracking system, she can now access the delivery tracking system",
                 "fail_message": "You check Anna's permissions, find that she has the correct permissions but she still cannot access the delivery tracking system",
                 "time_taken": 0.5
                 },
                 {"id": "2021",
                  "user": "Michael; Business Management",
                  "priority": "High",
                  "issue": "Unable to access business analytics dashboard, error message: 'Server not found'",
                  "option_1": "Check is business server is down, restart if needed",
                  "option_2": "Recover business analytics data from recent backups, restore if needed",
                  "correct_option": "option_1",
                  "success_message": "You check the business server, find that it is down and restart it, Michael can now access the business analytics dashboard",
                  "fail_message": "You recover business analytics data from recent backups, but the server is still down and Michael still cannot access the business analytics dashboard",
                  "time_taken": 1
                  },
                  {"id": "2023",
                   "user": "Samuel; Resource Management",
                   "priority": "Low",
                   "issue": "Unable to print resource reports, error message: 'Printer not found'",
                   "option_1": "Check if the printer is conected to the network, reconnect if needed",
                   "option_2": "Check if the user has the correct permissions, update if needed",
                   "correct_option": "option_1",
                   "success_message": "You check the printer, find that it is not connected to the network, you reconnect it and Samuel can now print resource reports",
                   "fail_message": "You check the users permissions, find that they have the correct permissions but they still cannot print resource reports",
                   "time_taken": 0.5
                   },
                   {"id": "2024",
                    "user": "Max; Web Development",
                    "priority": "Medium",
                    "issue": "Unable to deploy websites to production, error message: 'Deployment failed'",
                    "option_1": "Check if the deployment server is down, restart if needed",
                    "option_2": "Check deployment logs for errors, fix if needed",
                    "correct_option": "option_2",
                    "success_message": "You check the deployment logs, find that there was a missing dependency, you fix it and Max can now deploy websites to production",
                    "fail_message": "You check the deployment server, find that it is not down and Max still cannot deploy websites to production",
                    "time_taken": 1
                    },

        ]